# .goreleaser.yaml
project_name: test-sbom
builds:
  - id: test-app
    main: ./main.go
    binary: test-app
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  draft: false
  prerelease: auto
  mode: keep-existing
  #skip_upload: true  # Keep this as true

# Simple SBOM configuration
sboms:
  - id: source
    artifacts: source
  - id: archive
    artifacts: archive

signs:
- cmd: cosign
  # env:
  # - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: checksum
  output: true