# .goreleaser.yaml
project_name: test-sbom
builds:
  - id: test-app
    main: ./main.go
    binary: test-app
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  draft: false
  prerelease: auto
  mode: keep-existing
  #skip_upload: true  # Keep this as true

# Simple SBOM configuration
# sboms:
#   - artifacts: source
#   - id: binary
#     artifacts: binary
#     documents:
#       - "{{ .Binary }}_{{ .Os }}_{{ .Arch }}.sbom"

# signs:
# - cmd: cosign
#   env:
#   - COSIGN_EXPERIMENTAL=1
#   certificate: '${artifact}.pem'
#   args:
#     - sign-blob
#     - '--yes'
#     - '--output-certificate=${certificate}'
#     - '--output-signature=${signature}'
#     - '${artifact}'
#   artifacts: all
#   output: true